### ISSUE TITLE
[PE-D] Import seems to be not working

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-T11-2/tp#181]
After exporting LINGO.csv file using the `export` command. I cleared the app of flashcards and then proceeded to import LINGO.csv.
![Screenshot 2021-10-29 at 4.55.25 PM.png](https://raw.githubusercontent.com/CheahYan/ped/main/files/5308d42f-06b8-4a9c-9a6a-c3f9413c7556.png)

However, I am unable to do so. Not sure if i did it wrongly but exporting should put LINGO.csv file within the same folder as lingogo.jar file right? Thus, i shouldnt need to include a relative file path?

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: CheahYan/ped#5

**Comment by jhlee1997** [comment]
- Seems like the reviewer did not realize that import command takes in file path, not file name. Export would have created the "LINGO.csv" file in the data folder. To import that back in again, the user needs to "import data/LINGO.csv" instead of "import LINGO.csv".
- Now the import command takes in "CSV_FILE_NAME" as a parameter instead of "CSV_FILE_PATH. Thus, this issue will not happen again.
